// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiustoPrezzo.Migrations
{
    [DbContext(typeof(DbArticoli))]
    [Migration("20220207163615_Aggiunta default e rinominato campo URL immagine al DB")]
    partial class AggiuntadefaulterinominatocampoURLimmaginealDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Articolo", b =>
                {
                    b.Property<int>("ArticoloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAggiornamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<float>("GiustoPrezzo")
                        .HasColumnType("REAL");

                    b.Property<float>("PrezzoDue")
                        .HasColumnType("REAL");

                    b.Property<float>("PrezzoUno")
                        .HasColumnType("REAL");

                    b.Property<string>("UrlImmagine")
                        .HasColumnType("TEXT");

                    b.HasKey("ArticoloID");

                    b.ToTable("Articoli");
                });
#pragma warning restore 612, 618
        }
    }
}
