// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiustoPrezzo.Migrations
{
    [DbContext(typeof(DbArticoli))]
    partial class DbArticoliModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Articolo", b =>
                {
                    b.Property<int>("ArticoloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAggiornamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<float>("GiustoPrezzo")
                        .HasColumnType("REAL");

                    b.Property<float>("PrezzoDue")
                        .HasColumnType("REAL");

                    b.Property<float>("PrezzoUno")
                        .HasColumnType("REAL");

                    b.Property<string>("UrlImmagine")
                        .HasColumnType("TEXT");

                    b.HasKey("ArticoloID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Articolo", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany("Articles")
                        .HasForeignKey("CategoriaID");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
